fn main() {
    // App ACL manifest: the Settings → About update flow invokes the
    // `desktop-exit` command from the loopback-origin webview, which the ACL
    // gates (remote origins are not implicitly trusted). Autogenerated
    // permission: `allow-desktop-exit` (see capabilities/default.json).
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&["desktop-exit"]));
    tauri_build::try_build(attributes).expect("tauri-build failed");
}
